### PR TITLE
Rpc forwarding

### PR DESCRIPTION
**Pull request by dsagal**
This is a followup on #4 , another alternative for forwarding. See the test case for usage. It has its own pros and cons. I'll continue the discussion at #4 .

### CODE REVIEW

**Comment by dsagal** [comment]
@paulfitz Prompted me to follow up too, and I changed my PR to match my later cleaner proposal. I guess I feel that actual routing is overkill -- it would be useful if the topology were unknown (e.g. a node connects to multiple Rpc objects and the implementer doesn't know which calls to route where).

For our needs (and I guess any needs I can envision), the topology is known. E.g. this is how it would be for plugins, to expose unsafeNode to iframe:
```js
// On Grist server, support calls forwarded to "node"
gristBrowserRpc.registerForwarder("node", unsafeNodeComponentRpc);
// On Grist client, support calls forwarded to "node"
webWorkerRpc.registerForwarder("node", gristBrowserRpc, "node");
// In WebWorker, support calls forwarded to "node"
iframeRpc.registerForwarder("node", webWorkerRpc, "node");
// In iframe, get a stub that forwards calls to "node"
iframeRpc.getStubForward("node", "SomeUnsafeNodeAPI");
```
So as long as Grist provides the first two calls, the plugin author just needs to use the last two lines to call from iframe through webworker to unsafeNode.

**Comment by paulfitz** [comment]
One complicating factor I ran into was, when implementing a service within Grist for use in a plugin, having to spend a lot of time reasoning about topology in order to expose that service cleanly.

**Comment by dsagal** [comment]
I figured that some amount of such reasoning (like the two calls the plugin author would have to add to connect things up in my example) would have to be done in any case. Could you show how the use case from my example would be done using your proposal?

**Comment by paulfitz** [comment]
With my proposal, the plugin author would do:
```
iframeRpc.getStub<SomeUnsafeNodeAPI>("name");
```
Where `name` is that of whatever listener provides the service.

Your proposal is simpler and works.  For communication between different parts of a user's plugin, I think it is great, since they'll be aware of what their parts are called.  For communication with services offered by grist, it makes me itchy and nervous.  I'll have to name specific places within grist (server-part-that-is-closest-to-client, client-part-that-is-closest-to-server, server-part-that-is-closest-to-node, client-part-that-is-closest-to-browser-plugin) if I want to be able to implement services at the different loci. Alternatively I guess I could do some remapping just at the border with plugins to let the user think of everything as "grist" and add intelligence about internal routing as messages cross the border?

**Comment by dsagal** [comment]
Two questions:
1. Won’t the plugin author need to create endpoints too in their code?
2. Is message routing supported? E.g can a message be sent from an iframe
to unsafe node, or vice verse?

**Comment by paulfitz** [comment]
@dsagal for (1) using "my" PR for plugins as they are in grist today would require changing the boundaries a bit.  I'd put what I've been calling a node on the boundary, and then let authors hook up endpoints to it.  With the code I put up, like I say I think we end up with `with more kinds of names than needed`, it'd need iteration I think to get that right.

To sketch plugin code, assume `grist` object now has a node, I guess it'd be something like: `grist.getStub<ICalc>("backend", "calc")` on the front-end and `grist.registerImpl<ICalc>("backend", "calc", new Calc())` on the back-end.  Implemented that in terms of my PR is a bit clunky, but something like that is what I'd like.

For (2), yes messages routing should be supported, it is useful.

**Comment by paulfitz** [comment]
(for (2), just added a test that plain message routing works for networking PR)

**Comment by paulfitz** [comment]
For (1), I iterated a bit to implement the syntax I sketched (`grist.getStub<ICalc>("backend", "calc")` and `grist.registerImpl<ICalc>("backend, "calc", new Calc())` - see revised test.  However, it is basically all implemented as you feared, by wrapping Rpc and minting new Rpcs liberally.

**Pull request merged**
